In [1]:
import numpy as np

a=np.random.randn(5)
print(a)

[-0.30837329  1.01688808  0.53044533  1.67720953 -0.19401822]


In [2]:
print(a.shape) #rank 1 array. neither column, nor row vector

(5,)


### DO NOT USE RANK 1 ARRAYS

In [3]:
print(a.T)

[-0.30837329  1.01688808  0.53044533  1.67720953 -0.19401822]


In [4]:
print(np.dot(a, a.T))
# or use a.reshape(5,1)

4.261202599504148


### USE THIS

In [5]:
a=np.random.randn(5,1) # (5,1) matrix, column vector
print(a)

[[-0.94811698]
 [-0.81249092]
 [-0.40622166]
 [-1.06272826]
 [ 0.10880056]]


In [6]:
print(np.dot(a,a.T))

[[ 0.8989258   0.77033643  0.38514565  1.00759071 -0.10315566]
 [ 0.77033643  0.66014149  0.33005141  0.86345706 -0.08839947]
 [ 0.38514565  0.33005141  0.16501604  0.43170324 -0.04419715]
 [ 1.00759071  0.86345706  0.43170324  1.12939135 -0.11562543]
 [-0.10315566 -0.08839947 -0.04419715 -0.11562543  0.01183756]]


In [7]:
assert(a.shape==(5,1))

In [8]:
!jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [9]:
!jt -t chesterish