In [1]:
import numpy as np

a=np.random.randn(5)
print(a)

[ 0.49728504  1.75995698  2.19267978  0.60419206 -0.0648476 ]


In [2]:
print(a.shape) #rank 1 array. neither column, nor row vector

(5,)


### DO NOT USE RANK 1 ARRAYS

In [3]:
print(a.T)

[ 0.49728504  1.75995698  2.19267978  0.60419206 -0.0648476 ]


In [4]:
print(np.dot(a, a.T))
# or use a.reshape(5,1)

8.521838829526265


### USE THIS

In [7]:
a=np.random.randn(5,1) # (5,1) matrix, column vector
print(a)

[[-0.20187752]
 [-0.36781135]
 [-0.88677981]
 [-0.77789897]
 [-0.24795015]]


In [8]:
print(np.dot(a,a.T))

[[0.04075453 0.07425284 0.17902091 0.15704031 0.05005556]
 [0.07425284 0.13528519 0.32616768 0.28612007 0.09119888]
 [0.17902091 0.32616768 0.78637843 0.6898251  0.21987719]
 [0.15704031 0.28612007 0.6898251  0.6051268  0.19288016]
 [0.05005556 0.09119888 0.21987719 0.19288016 0.06147928]]


In [10]:
assert(a.shape==(5,1))